### ISSUE TITLE
Add publish workflow

### ISSUE THREAD

**Issue by uripeled2** [uripeled2/llm-client-sdk#23]
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

**Comment by aharonYK** [comment]
hey can i help u with that?

**Comment by uripeled2** [comment]
@aharonYK Yes thank you, do you need any guidance or more details?

**Comment by aharonYK** [comment]
@uripeled2  not for now..
thanks!!

**Comment by aharonYK** [comment]
in the exsamle you showed me they use :
user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          
          do you want it ?
          because i dont have the necessary credentials to authenticate with PyPI

**Comment by uripeled2** [comment]
Yes, you can open a PR and I will add the necessary secrets
