### ISSUE TITLE
Add p-top to common models parameter

### ISSUE THREAD

**Issue by uripeled2** [uripeled2/llm-client-sdk#28]
Add p-top (here is OpenAI docs on [p-top](https://platform.openai.com/docs/api-reference/chat/create#chat/create-top_p)) as a param in BaseLLMAPIClient.text_completion.
You can take a look at this great [PR](https://github.com/uripeled2/llm-client-sdk/commit/11c56055c4d67bae9c9a6b8b49faad8a6fbe9eed) done by @EyalPaz-700 and see how he added max_tokens and temperature into BaseLLMAPIClient.text_completion params

**Comment by EyalPaz-700** [comment]
https://github.com/uripeled2/llm-client-sdk/pull/29
